package main

import (
	"crypto/tls"
	"crypto/x509"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net"
	"net/http"
	"net/netip"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/miekg/dns"
	"github.com/oschwald/maxminddb-golang/v2"
	"gopkg.in/yaml.v3"
)

type ConfigRule struct {
	Name       string   `yaml:"name"`
	Continent  string   `yaml:"cont"`
	Country    []string `yaml:"cc"`
	RegCountry []string `yaml:"regcc"`
	ASN        []int    `yaml:"asn"`
	Result     string   `yaml:"result"`
}

// configuration structure
type Config struct {
	Listen     string       `yaml:"listen"`     // clients connect to us e.g. "[::]:53"
	GeoDb      string       `yaml:"geodb"`      // path to geo-ip database (.mmdb)
	ASNDb      string       `yaml:"asndb"`      // path to asn-ip database (.mmdb)
	Domain     string       `yaml:"domain"`     // domain name we respond to (we REFUSE everything else)
	Nameserver string       `yaml:"ns"`         // nameserver name (fqdn)
	Rname      string       `yaml:"rname"`      // rname/mailbox (for soa record)
	Rules      []ConfigRule `yaml:"rules"`      // downstream interfaces
	TlsKey     string       `yaml:"tls_key"`    //TLS key file
	TlsCert    string       `yaml:"tls_cert"`   //TLS cert file
	TlsClient  string       `yaml:"tls_client"` //TLS client certificate authority
	WebListen  string       `yaml:"web_listen"` //Listen for the web portion
}

var cfg Config

// load config
func loadConfig(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	if err := yaml.NewDecoder(f).Decode(&cfg); err != nil {
		return err
	}

	//validate listen
	if cfg.Listen == "" {
		log.Printf("Listen not specified, using default")
		cfg.Listen = "[::]:53"
	}

	//validate domain is fully qualified
	if !strings.HasSuffix(cfg.Domain, ".") {
		return fmt.Errorf("Domain not specified or not fully-qualified (must end with .)")
	}

	//validate nameserver is fully qualified
	if !strings.HasSuffix(cfg.Nameserver, ".") {
		return fmt.Errorf("Nameserver not specified or not fully-qualified (must end with .)")
	}

	//validate rname is fully qualified
	if !strings.HasSuffix(cfg.Rname, ".") {
		return fmt.Errorf("Rname not specified or not fully-qualified (must end with .)")
	}

	//validate web listen
	if cfg.WebListen == "" {
		log.Printf("WebListen not specified, using default")
		cfg.WebListen = "[::]:8080"
	}

	return nil
}

type GeoRecord struct {
	Country struct {
		ISOCode string            `maxminddb:"iso_code"`
		Names   map[string]string `maxminddb:"names"`
	} `maxminddb:"country"`
	RegCountry struct {
		ISOCode string            `maxminddb:"iso_code"`
		Names   map[string]string `maxminddb:"names"`
	} `maxminddb:"registered_country"`
	Continent struct {
		Code string `maxminddb:"code"`
	} `maxminddb:"continent"`
}

type ASNRecord struct {
	ASN int    `maxminddb:"autonomous_system_number"`
	Org string `maxminddb:"autonomous_system_organization"`
}

var GeoDb *maxminddb.Reader
var ASNDb *maxminddb.Reader

// load geodb
func loadGeoDb() {
	//load country/city db
	db, err := maxminddb.Open(cfg.GeoDb)
	if err != nil {
		log.Fatal(err)
	}
	GeoDb = db

	//load asn db (not sure why they can't merge these)
	adb, aerr := maxminddb.Open(cfg.ASNDb)
	if err != nil {
		log.Fatal(aerr)
	}
	ASNDb = adb
}

func queryGeoDb(src netip.Addr) GeoRecord {
	var record GeoRecord
	err := GeoDb.Lookup(src).Decode(&record)
	if err != nil {
		log.Fatal(err)
	}
	return record
}

func queryASNDb(src netip.Addr) ASNRecord {
	var record ASNRecord
	err := ASNDb.Lookup(src).Decode(&record)
	if err != nil {
		log.Fatal(err)
	}
	return record
}

type DbEcsEntry struct {
	Present bool
	Addr    net.IP
	Mask    uint8
	Geo     GeoRecord
	ASN     ASNRecord
}

// database structure
type DbEntry struct {
	//data related to DNS query
	dnsECS  DbEcsEntry
	dnsTime time.Time
	dnsSrc  string
	dnsGeo  GeoRecord
	dnsASN  ASNRecord
	dnsRule string
	//data related to HTTP queries
	queriedAt time.Time
}

// database itself
var QueryDb map[uint32]DbEntry

// the soa for our domain
// generated by listenAndServeDNS
var soa *dns.SOA

// handle a DNS request
func handleDNSRequest(w dns.ResponseWriter, req *dns.Msg) {

	//convert qtype into string for logging later
	q := req.Question[0]
	qTypeStr := strconv.Itoa(int(q.Qtype))
	switch q.Qtype {
	case dns.TypeA:
		qTypeStr = "A"
	case dns.TypeAAAA:
		qTypeStr = "AAAA"
	case dns.TypeCNAME:
		qTypeStr = "CNAME"
	case dns.TypeNS:
		qTypeStr = "NS"
	case dns.TypeSRV:
		qTypeStr = "SRV"
	case dns.TypePTR:
		qTypeStr = "PTR"
	case dns.TypeHTTPS:
		qTypeStr = "HTTPS"
	}

	// RemoteAddr() is available directly on ResponseWriter
	remoteAddr := w.RemoteAddr()

	// Extract just the IP (strips the port)
	clientIP, _, err := net.SplitHostPort(remoteAddr.String())
	if err != nil {
		// RemoteAddr had no port (unlikely but safe to handle)
		clientIP = remoteAddr.String()
	}

	//conver to netIP
	reqIP, err := netip.ParseAddr(clientIP)
	if err != nil {
		// invalid?
		log.Printf("Unable to parse netIP: %s", clientIP)
		return
	}

	//validate that query is for our domain (DNS will randomize case)
	if !strings.EqualFold(q.Name, cfg.Domain) {
		log.Printf("Got query of invalid name: [%s] %s", qTypeStr, q.Name)
		m := new(dns.Msg)
		m.SetRcode(req, dns.RcodeRefused)
		_ = w.WriteMsg(m)
		return
	}

	//check if question is not an AAAA -> return NOERROR / NOANSWER
	//need SOA record for this one
	if q.Qtype != dns.TypeAAAA && q.Qtype != dns.TypeTXT {
		log.Printf("Got query of incorrect type: [%s] from %s", qTypeStr, clientIP)
		m := new(dns.Msg)
		m.SetRcode(req, dns.RcodeSuccess)
		m.Ns = []dns.RR{soa}
		m.Authoritative = true
		_ = w.WriteMsg(m)
		return
	}

	id := rand.Uint32()
	var entry DbEntry

	log.Printf("Got query of correct type: [%s] uid %d", qTypeStr, id)
	entry.dnsTime = time.Now()
	entry.dnsSrc = clientIP

	log.Printf("Query from IP: %s", clientIP)

	dnsGeo := queryGeoDb(reqIP)
	entry.dnsGeo = dnsGeo
	if entry.dnsGeo.Country.ISOCode != "" {
		log.Printf("Query from CC: %s", entry.dnsGeo.Country.ISOCode)
		log.Printf("Query from reg CC: %s", entry.dnsGeo.RegCountry.ISOCode)
		log.Printf("Query from continent: %s", entry.dnsGeo.Continent.Code)
	} else {
		log.Printf("Query from invald CC")
	}

	dnsASN := queryASNDb(reqIP)
	entry.dnsASN = dnsASN
	log.Printf("Query from ASN: %d [%s]", entry.dnsASN.ASN, entry.dnsASN.Org)

	// get edns client subnet
	subnet := getECS(req)
	if subnet != nil {
		var ecs DbEcsEntry
		log.Printf("Query has ECS information present")
		log.Printf("ECS Address:        %s", subnet.Address)
		log.Printf("ECS Source prefix:  %d", subnet.SourceNetmask)
		log.Printf("ECS Family:         %d (1=IPv4, 2=IPv6)", subnet.Family)
		ecs.Addr = subnet.Address
		ecs.Mask = subnet.SourceNetmask
		geo, _ := netip.ParseAddr(subnet.Address.String())
		ecs.Geo = queryGeoDb(geo)
		ecs.ASN = queryASNDb(geo)
		ecs.Present = true
		log.Printf("ECS Country Code:   %s", ecs.Geo.Country.ISOCode)
		log.Printf("ECS Registration CC:%s", ecs.Geo.RegCountry.ISOCode)
		log.Printf("ECS Continent:      %s", ecs.Geo.Continent.Code)
		log.Printf("ECS ASN:            %d [%s]", ecs.ASN.ASN, ecs.ASN.Org)
		entry.dnsECS = ecs
		//use ECS data for geo localization
		dnsGeo = ecs.Geo
		dnsASN = ecs.ASN

		//return ecs with same length as source mask (this is the length we did the lookup with)
	} else {
		log.Println("No EDNS Client Subnet in query")
	}

	//perform rule lookup in order
	var rule *ConfigRule
	for _, thisRule := range cfg.Rules {
		//If it has a continent, make sure it matches
		if len(thisRule.Continent) > 0 {
			//If it does not match, exit
			if thisRule.Continent != dnsGeo.Continent.Code {
				continue
			}
		}
		//If this rule has an ASN, check that we are in the list
		if len(thisRule.ASN) > 0 {
			if !slices.Contains(thisRule.ASN, dnsASN.ASN) {
				continue
			}
		}
		//If this rule has a RegCountry, check that we are in the list
		if len(thisRule.RegCountry) > 0 {
			if !slices.Contains(thisRule.RegCountry, dnsGeo.RegCountry.ISOCode) {
				continue
			}
		}
		//If this rule has a Country, check that we are in the list
		if len(thisRule.Country) > 0 {
			if !slices.Contains(thisRule.Country, dnsGeo.Country.ISOCode) {
				continue
			}
		}
		//This rule matches!
		rule = &thisRule
		break
	}

	entry.dnsRule = "NONE"
	if rule != nil {
		entry.dnsRule = rule.Name
	}

	//If this is a TXT query, return all this data as a TXT
	if q.Qtype == dns.TypeTXT {

		log.Printf("Returning TXT query")
		m := new(dns.Msg)
		m.SetRcode(req, dns.RcodeSuccess)
		m.Authoritative = true
		//geo we ended up using for location
		m.Answer = append(m.Answer, &dns.TXT{
			Hdr: dns.RR_Header{
				Name:   req.Question[0].Name, // use the queried name
				Rrtype: dns.TypeTXT,
				Class:  dns.ClassINET,
				Ttl:    300,
			},
			Txt: []string{fmt.Sprintf("Geo cc=%s regcc=%s cont=%s asn=%d",
				dnsGeo.Country.ISOCode,
				dnsGeo.RegCountry.ISOCode,
				dnsGeo.Continent.Code,
				dnsASN.ASN)},
		})
		//original geo query
		m.Answer = append(m.Answer, &dns.TXT{
			Hdr: dns.RR_Header{
				Name:   req.Question[0].Name, // use the queried name
				Rrtype: dns.TypeTXT,
				Class:  dns.ClassINET,
				Ttl:    300,
			},
			Txt: []string{fmt.Sprintf("OrigGeo cc=%s regcc=%s cont=%s asn=%d",
				entry.dnsGeo.Country.ISOCode,
				entry.dnsGeo.RegCountry.ISOCode,
				entry.dnsGeo.Continent.Code,
				entry.dnsASN.ASN)},
		})
		//ecs (if present)
		if subnet != nil {
			m.Answer = append(m.Answer, &dns.TXT{
				Hdr: dns.RR_Header{
					Name:   req.Question[0].Name, // use the queried name
					Rrtype: dns.TypeTXT,
					Class:  dns.ClassINET,
					Ttl:    300,
				},
				Txt: []string{fmt.Sprintf("ECSGeo cc=%s regcc=%s cont=%s asn=%d",
					entry.dnsECS.Geo.Country.ISOCode,
					entry.dnsECS.Geo.RegCountry.ISOCode,
					entry.dnsECS.Geo.Continent.Code,
					entry.dnsECS.ASN.ASN)},
			})
		}
		//rule we hit
		if rule != nil {
			m.Answer = append(m.Answer, &dns.TXT{
				Hdr: dns.RR_Header{
					Name:   req.Question[0].Name, // use the queried name
					Rrtype: dns.TypeTXT,
					Class:  dns.ClassINET,
					Ttl:    300,
				},
				Txt: []string{fmt.Sprintf("Rule=%s", rule.Name)},
			})
		} else {
			m.Answer = append(m.Answer, &dns.TXT{
				Hdr: dns.RR_Header{
					Name:   req.Question[0].Name, // use the queried name
					Rrtype: dns.TypeTXT,
					Class:  dns.ClassINET,
					Ttl:    300,
				},
				Txt: []string{fmt.Sprintf("Rule=NONE", rule.Name)},
			})
		}
		_ = w.WriteMsg(m)
		return
	}

	//therefore, we must return aaaa
	m := new(dns.Msg)

	//If we hit a rule, add it to the replies section
	if rule != nil {
		//compute address w/ id
		//I hate this string conv but it works
		NewPref, _ := netip.ParsePrefix(rule.Result)
		NewIPStr := NewPref.Addr().String() + fmt.Sprintf("%4x:%4x", uint16((id&0xffff0000)>>16), uint16(id&0x0000ffff))
		NewIP := net.ParseIP(NewIPStr)
		log.Printf("New IP is %v", NewIP)
		m.Answer = append(m.Answer, &dns.AAAA{
			Hdr: dns.RR_Header{
				Name:   req.Question[0].Name, // use the queried name
				Rrtype: dns.TypeAAAA,
				Class:  dns.ClassINET,
				Ttl:    60,
			},
			AAAA: NewIP,
		})
	}

	//store data in db only for aaaa queries
	QueryDb[id] = entry

	log.Printf("DB now has %d entries", len(QueryDb))

	m.SetRcode(req, dns.RcodeSuccess)
	m.Authoritative = true
	_ = w.WriteMsg(m)
}

// parse opt for edns client subnet
func getECS(r *dns.Msg) *dns.EDNS0_SUBNET {
	opt := r.IsEdns0()
	if opt == nil {
		return nil // No OPT record at all
	}

	for _, option := range opt.Option {
		if subnet, ok := option.(*dns.EDNS0_SUBNET); ok {
			return subnet
		}
	}
	return nil
}

// statically configure an SOA record
func genSOA() {
	//gen timestamp for SOA record
	curSerial, _ := strconv.Atoi(time.Now().Format("2006010215"))
	soa = &dns.SOA{
		Hdr:     dns.RR_Header{Name: cfg.Domain, Rrtype: dns.TypeSOA, Class: dns.ClassINET, Ttl: 300},
		Ns:      cfg.Nameserver,
		Mbox:    cfg.Rname,
		Serial:  uint32(curSerial),
		Refresh: 3600,
		Retry:   900,
		Expire:  604800,
		Minttl:  300, // negative caching TTL per RFC 2308
	}
}

// listen and serve DNS
func listenAndServeDNS() {
	//gen new SOA record
	genSOA()

	//create new dns server
	mux := dns.NewServeMux()
	mux.HandleFunc(".", handleDNSRequest)

	server := &dns.Server{
		Addr:    cfg.Listen,
		Net:     "udp",
		Handler: mux,
	}

	log.Printf("DNS server listening on %s", cfg.Listen)
	log.Fatal(server.ListenAndServe())
}

// web result handler
func handleWebReq(w http.ResponseWriter, req *http.Request) {
	log.Printf("Got a web request!")
	//get forwarded ip
	if xri := req.Header.Get("X-Real-IP"); xri != "" {
		fmt.Fprintf(w, "Your IP (of the HTTP connection) is %s\n", xri)
		reqIP, err := netip.ParseAddr(xri)
		if err != nil {
			// invalid?
			log.Printf("Unable to parse your IP: %s", err)
		} else {
			geo := queryGeoDb(reqIP)
			asn := queryASNDb(reqIP)
			fmt.Fprintf(w, "\tThis address is geo-located to <b>[%s][%s] %s</b>\n",
				geo.Continent.Code,
				geo.Country.ISOCode,
				geo.Country.Names["en"])
			fmt.Fprintf(w, "\tThis prefix is owned by AS <b>#%d [%s]</b>, registered in <b>[%s] %s</b>\n",
				asn.ASN,
				asn.Org,
				geo.RegCountry.ISOCode,
				geo.RegCountry.Names["en"])
		}
	}
	//get server ip
	if xri := req.Header.Get("X-Server-IP"); xri != "" {
		fmt.Fprintf(w, "You connected to the server at IP %s\n", xri)

		//extract 32 lsbs
		ServerIP, err := netip.ParseAddr(xri)
		if err != nil {
			//bail
			fmt.Fprintf(w, "Error parsing X-Server-IP as an address: %v\n", err)
		} else if ServerIP.Is6() {
			//extract lower 32 bytes of the ipv6 addr
			addr6 := ServerIP.As16()
			uid := uint32(addr6[12])<<24 | uint32(addr6[13])<<16 | uint32(addr6[14])<<8 | uint32(addr6[15])
			fmt.Fprintf(w, "Extracted uid %d\n", uid)
			//get that db entry
			entry, found := QueryDb[uid]
			if found {
				fmt.Fprintf(w, "The DNS request which sent you here came from IP address <b>%s</b>\n",
					entry.dnsSrc)
				fmt.Fprintf(w, "\t(This is the address of your resolver, which may be your ISPs, or a public resolver)\n")
				fmt.Fprintf(w, "\tThis address is geo-located to <b>[%s][%s] %s</b>\n",
					entry.dnsGeo.Continent.Code,
					entry.dnsGeo.Country.ISOCode,
					entry.dnsGeo.Country.Names["en"])
				fmt.Fprintf(w, "\tThis address is in a prefix owned by AS <b>#%d [%s]</b>, registered in <b>[%s] %s</b>\n",
					entry.dnsASN.ASN,
					entry.dnsASN.Org,
					entry.dnsGeo.RegCountry.ISOCode,
					entry.dnsGeo.RegCountry.Names["en"])
				if entry.dnsECS.Present {
					fmt.Fprintf(w, "Your DNS request included EDNS Client Subnet (ECS) request,\n")
					fmt.Fprintf(w, "\tThis indicates a source IP range <b>%s/%d</b>\n",
						entry.dnsECS.Addr,
						entry.dnsECS.Mask)
					fmt.Fprintf(w, "\tThis address is geo-located to <b>[%s][%s] %s</b>\n",
						entry.dnsECS.Geo.Continent.Code,
						entry.dnsECS.Geo.Country.ISOCode,
						entry.dnsECS.Geo.Country.Names["en"])
					fmt.Fprintf(w, "\tThis prefix is owned by AS <b>#%d [%s]</b>, registered in <b>[%s] %s</b>\n",
						entry.dnsECS.ASN.ASN,
						entry.dnsECS.ASN.Org,
						entry.dnsECS.Geo.RegCountry.ISOCode,
						entry.dnsECS.Geo.RegCountry.Names["en"])
				} else {
					fmt.Fprintf(w, "Your DNS request did not include EDNS Client Subnet (ECS)\n")
				}
			} else {
				fmt.Fprintf(w, "Unable to match request to a DNS query!\n")
			}
			fmt.Fprintf(w, "Based on your dns query, we matched you via rule name <b>[%s]</b>]n", entry.dnsRule)
		} else {
			fmt.Fprintf(w, "Your are not connected via IPv6, so I can't provide DNS information, sorry\n")
		}
	}
	//dump all headers
	fmt.Fprintf(w, "Your request (over HTTP) contained all of these headers:\n")
	for name, values := range req.Header {
		fmt.Fprintf(w, "\t%s: %s\n", name, strings.Join(values, ", "))
	}
}

// stats handler
func handleWebStats(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "Hello Stats\n")
}

// web listen and serve
func listenAndServeHTTP() {
	//request handlers
	handler := http.NewServeMux()
	handler.HandleFunc("/data", handleWebReq)
	handler.HandleFunc("/stats", handleWebStats)

	server := http.Server{
		Addr:    cfg.WebListen,
		Handler: handler,
	}

	//if we are doing TLS
	if len(cfg.TlsCert) > 0 && len(cfg.TlsKey) > 0 {

		//If we are doing mTLS
		if len(cfg.TlsClient) > 0 {
			caCertFile, err := os.ReadFile(cfg.TlsClient)
			if err != nil {
				log.Fatalf("error reading CA certificate: %v", err)
			}
			caCertPool := x509.NewCertPool()
			caCertPool.AppendCertsFromPEM(caCertFile)

			// Create the TLS Config with the CA pool and enable Client certificate validation
			tlsConfig := &tls.Config{
				ClientCAs:  caCertPool,
				ClientAuth: tls.RequireAndVerifyClientCert,
			}
			tlsConfig.BuildNameToCertificate()

			// update tlsConfig
			server.TLSConfig = tlsConfig
			log.Printf("Requiring TLS Client Certificates")
		}

		log.Printf("Go to https://%s/", cfg.WebListen)
		log.Fatal(server.ListenAndServeTLS(cfg.TlsCert, cfg.TlsKey))
	}

	log.Printf("Go to http://%s/", cfg.WebListen)
	log.Fatal(server.ListenAndServe())
}

// main function
func main() {
	//allocate map
	QueryDb = make(map[uint32]DbEntry)

	//load config file
	configPath := flag.String("conf", "dnsprint.yaml", "path to config file")
	flag.Parse()

	err := loadConfig(*configPath)
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	//load geo db
	loadGeoDb()
	defer GeoDb.Close()

	//run the http server
	go listenAndServeHTTP()

	//run the dns server
	go listenAndServeDNS()

	//sit in a loop and periodically purge old cache entries
	for {
		log.Printf("Doing regular db purge...")
		//go through the loop and delete anything older than 12 hours
		for key := range QueryDb {
			//how old is entry?
			if time.Now().Sub(QueryDb[key].dnsTime).Hours() >= 12 {
				delete(QueryDb, key)
			}
		}
		//now wait 5 minutes to next trim
		time.Sleep(5 * time.Minute)
	}
}
